### PR TITLE
[refactor] Optimize LLM execution by moving source retrieval to server-side

### PR DESCRIPTION
**Pull request by toyamarinyon**
## Changes
- Modified LLM execution flow to handle source code retrieval on server-side
- Implemented source index-based retrieval system
- Removed direct source code transmission from client
- Added server-side source code embedding in prompts

## Why
This change improves the system architecture by:
1. Reducing network traffic between client and server
2. Improving security by keeping source code handling server-side
3. Centralizing source code management
4. Creating a more efficient source retrieval process using indices

## Verification Steps
The following operations should work without regression:

- [ ] 1. Text Generator Node
    - [ ] Place a Text Generator node
    - [ ] Enter text and press Push Value
    - [ ] Verify text generation works

- [ ] 2. Web Search Node
    - [ ] Place a Web Search node
    - [ ] Enter text and press Push Value
    - [ ] Verify search results are generated

- [ ] 3. Prompt Node Source Operations
    - [ ] Add text content and verify text generation
    - [ ] Add file and verify text generation
    - [ ] Add Text Generator artifacts and verify text generation
    - [ ] Add Web Search artifacts and verify text generation

### CODE REVIEW

**Comment by shige** [comment]
@toyamarinyon https://github.com/route06inc/giselle/pull/57#issuecomment-2445866716 was merged into the main branch an hour ago. 
Could you please merge or rebase it with the latest main branch to resolve the Queued status in GitHub Actions?

**Comment by masutaka** [comment]
I'm not sure, It might be better to cancel the jobs that are currently running. Something is wrong. It is very strange. Something is wrong.
https://github.com/route06inc/giselle/actions
e.g. https://github.com/route06inc/giselle/actions/runs/11588098366/job/32261395602

**Comment by masutaka** [comment]
There may be a problem with GitHub Actions.
https://x.com/search?q=github&src=typed_query&f=live

But I can't see the fault at https://www.githubstatus.com/ .

**Comment by shige** [comment]
> There may be a problem with GitHub Actions. https://x.com/search?q=github&src=typed_query&f=live

Got it! Let's wait for the recovery. 🙏

**Comment by masutaka** [comment]
I cancelled all jobs because they could be charged. But jobs are still queued. 😅
https://github.com/route06inc/giselle/actions

**Comment by toyamarinyon** [comment]
@shige All checks have passed successfully!

**Comment by shige** [comment]
Thanks, I'll review it right now!

**Review by shige — APPROVED** [review]
LGTM 👍 

---

**OAT**

- [x] 1. Text Generator Node
    - [x] Place a Text Generator node
    - [x] Enter text and press Push Value
    - [x] Verify text generation works
- [x] 2. Web Search Node
    - [x] Place a Web Search node
    - [x] Enter text and press Push Value
    - [x] Verify search results are generated
- [x] 3. Prompt Node Source Operations
    - [x] Add text content and verify text generation
    - [x] Add file and verify text generation
    - [x] Add Text Generator artifacts and verify text generation
    - [x] Add Web Search artifacts and verify text generation

**Pull request merged**
