### PR TITLE
Add Viewer mode and isFinal flag to prepare for flow execution

### PR DESCRIPTION
**Pull request by toyamarinyon**
## Overview
Added initial preparation for flow execution functionality in Playground.

## Changes
- Added Viewer component alongside existing Editor
- Implemented mode switching between Editor and Viewer
- Added `isFinal` flag to nodes to identify terminal nodes in the flow

## Details
Previously, Playground only had Editor functionality without a way to view flow execution results. This PR adds a basic Viewer component structure (currently empty) and the ability to switch between Editor and Viewer modes.

Additionally, introduced an `isFinal` flag to nodes to help identify which nodes represent the end of a flow, which will be necessary for proper flow execution.

## Release Flow:
Since this includes database migrations, please merge and run the script `./scripts/20241023-db-patch-finalv2.ts` after approval.

### CODE REVIEW

**Comment by shige** [comment]
@toyamarinyon Let me know 👂 
 
When is it expected that the VIEW mode and the Run button will become available? 
If we merge this now, it will release features that are not yet usable, which I believe will cause confusion among existing users.

**Comment by toyamarinyon** [comment]
@shige I understand your point. While we could hide these features behind a Feature Flag, since these changes don't affect terms of service or privacy policy, I think it might be acceptable to show features that are still under development.

**Comment by shige** [comment]
@toyamarinyon 
What I meant was that we can't release something that simply doesn't work. 
Once the VIEW Mode and RUN button are working, we will merge and deploy, so please let me know.

**Comment by toyamarinyon** [comment]
@shige I understand. However, if we wait until everything is fully functional, the diff will become quite large. So I'll implement a Feature Flag to disable these features, which will allow us to merge now.

**Comment by shige** [comment]
I agree. 👍

**Comment by toyamarinyon** [comment]
I've disabled the VIEW mode toggle and Run button by default using the Feature Flag. These elements will not be displayed when the Feature Flag is turned off (default state).

### Default 

image

### Override

image

**Comment by toyamarinyon** [comment]
@shige Could you verify these changes?

**Review by shige — APPROVED** [review]
LGTM 👍 

Tomorrow morning, I'll deploy them and migrate db data. 📆

**Comment by shige** [comment]
> Tomorrow morning, I'll deploy them and migrate db data. 📆

Done!

```sh
$ bun scripts/20241023-db-patch-finalv2.ts

Starting the update of agent data to set 'isFinal' property on nodes.
Updating 72 agents...
  ├ Processing chunk 1/8 (10 agents)
  │ └ Completed chunk 1/8
  ├ Processing chunk 2/8 (10 agents)
  │ └ Completed chunk 2/8
  ├ Processing chunk 3/8 (10 agents)
  │ └ Completed chunk 3/8
  ├ Processing chunk 4/8 (10 agents)
  │ └ Completed chunk 4/8
  ├ Processing chunk 5/8 (10 agents)
  │ └ Completed chunk 5/8
  ├ Processing chunk 6/8 (10 agents)
  │ └ Completed chunk 6/8
  ├ Processing chunk 7/8 (10 agents)
  │ └ Completed chunk 7/8
  ├ Processing chunk 8/8 (2 agents)
  │ └ Completed chunk 8/8
All agents have been successfully updated!
```

**Comment by shige** [comment]
All done ✅ 
- [x] deployed to production
- [x] migrated db data
- [x] confirmed the operation

JFYI @toyamarinyon

**Pull request merged**
