### PR TITLE
Next 15 stable

### PR DESCRIPTION
**Pull request by toyamarinyon**
Updated to Next.js 15 as it's now stable. Will merge after confirming there are no regressions.

### Verification Steps
The following operations should work without regression:

- [ ] Verification of No Regression

    - [ ] 1. Text Generator Node
        - [ ] Place a Text Generator node
        - [ ] Enter text and press Push Value
        - [ ] Verify text generation works
    
    - [ ] 2. Web Search Node
        - [ ] Place a Web Search node
        - [ ] Enter text and press Push Value
        - [ ] Verify search results are generated
    
    - [ ] 3. Prompt Node Source Operations
        - [ ] Add text content and verify text generation
        - [ ] Add file and verify text generation
        - [ ] Add Text Generator artifacts and verify text generation
        - [ ] Add Web Search artifacts and verify text generation
  
    - [ ] Verify that the flow executes sequentially when pressing the Run Button
            
        > [!NOTE]
        > Currently, you need to connect two or more flows, so please connect the flows and verify.
        
        image

        - [ ] 1. Press the Run button
        - [ ] 2. Switch to View screen
        - [ ] 3. Flow executes sequentially
        - [ ] 4. Click tabs on the left side to check execution status of each flow

### CODE REVIEW

**Comment by toyamarinyon** [comment]
Although it shows as 'Failed' in the image, it is now working after redeploying from the Vercel dashboard.

image

**Review by shige — APPROVED** [review]
LGTM! 🆙

**Comment by toyamarinyon** [comment]
Thank you for checking! After making some adjustments, I realized that it would be better for future development to make several adjustments before upgrading the Next.js version, so I will close this Pull request and create a new one.

**Comment by toyamarinyon** [comment]
I re-create pull request https://github.com/route06inc/giselle/pull/72

**Pull request closed without merging**
