### PR TITLE
Migrate NOTICE.md to License report

### PR DESCRIPTION
**Pull request by masutaka**
## Summary

Up until now, I used to manually put licenses that might need a credit notation in `Notice.md`.

I added the license report `docs/packages-license.md` and made it auto-update so that `Notice.md` is no longer needed.

Also I stopped uploading license reports as artifact.

## Related Issue

Nothing

## Testing

`docs/packages-license.md` was successfully committed by GitHub Actions.

https://github.com/route06inc/giselle/blob/migrate-notice-md-to-license-html-report/docs/packages-license.md

## Other Information

* HTML files are not rendered on GitHub, so I committed a Markdown file
* There was a problem that committing in GitHub Actions did not trigger required checks that should be triggered by that commit. Therefore, I created a GitHub App to create a token for each commit
    * Registered the Repository variable `CI_TRIGGER_APP_ID`
    * Registered Repository secret `CI_TRIGGER_APP_PRIVATE_KEY`
* Changed dorny/paths-filter to actions/cache to avoid infinite execution of GitHub Actions
    * thx! https://github.com/route06inc/giselle/pull/18#pullrequestreview-2374415413

### CODE REVIEW

**Comment by masutaka** [comment]
Since ebaf17ea519ed7eb53e079f4f3f2fd02f560db21 is a commit by Bot, these jobs are not triggered...

image

**Review by shige — APPROVED** [review]
LGTM 🆙

**Review by toyamarinyon — APPROVED** [review]
Great!!!

**Comment by masutaka** [comment]
Thanks for your review!

**Comment by masutaka** [comment]
✅ Testing on the `main` branch was as expected; `docs/packages-license.md` was not updated.
https://github.com/route06inc/giselle/actions/runs/11510164791/job/32041505556

**Pull request merged**
